### ISSUE TITLE
[BUG] Invalid Node Version!

### ISSUE THREAD

**Issue by ducky710** [tycrek/ass#27]
## Expected Behavior
ass runs
## Actual Behavior
ass says invalid node version even though it ran with this node version two days ago
```
Invalid node version!
- Current: 16.4.1
- Required: >=14.7.0 <16.0.0
Please update to continue!
```

**Comment by tycrek** [comment]
This is due to commit https://github.com/tycrek/ass/commit/9f4801a4e35648e27589fc89e048457ffaf68c72. Bug here https://github.com/LinusU/fs-temp/pull/6 needs to be merged and published before I can support 16.0.0 properly again.

Another user in the Support Discord was unable to have any files saved on Node 16 due to this bug, so I can't "officially" support that version at this time (I will again once that PR is merged). If you want to force allow it in case your install of Node does work, you can modify `package.json` to either:

1) Remove version cap here https://github.com/tycrek/ass/blob/master/package.json#L7 (just remove ` <16`)
2) Remove `prestart` script here https://github.com/tycrek/ass/blob/master/package.json#L20

**Comment by ducky710** [comment]
Oh okay I see. So should i downgrade to Node 14? I'm not sure it does work actually. I can't upload anything to it without it erroring

```
Jul 12, 2021, 10:40 PM [INFO]    * ass v0.7.4 *

Jul 12, 2021, 10:40 PM [INFO]    Users: 1
Jul 12, 2021, 10:40 PM [INFO]    Files: 0
Jul 12, 2021, 10:40 PM [INFO]    StorageEngine: JSON (file)
Jul 12, 2021, 10:40 PM [INFO]    Frontend: disabled
Jul 12, 2021, 10:40 PM [INFO]    Index redirect: disabled

Jul 12, 2021, 10:40 PM [Express] Express started: Listening on 0.0.0.0:60606 (click http://127.0.0.1:60606/)
Jul 12, 2021, 10:40 PM [SUCCESS] Ready for uploads: Storing resources on disk
Jul 12, 2021, 10:40 PM [Express] HTTP POST: /
Jul 12, 2021, 10:40 PM [ERROR]   Unhandled Promise rejection: The "path" argument must be of type string or an instance of Buffer or URL. Received null ([object Promise])
TypeError [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string or an instance of Buffer or URL. Received null
    at TempWriteStream.WriteStream (node:internal/fs/streams:360:5)
    at new TempWriteStream (/home/ass-releases-0.7.4/node_modules/fs-temp/lib/write-stream.js:6:15)
    at Object.createWriteStream (/home/ass-releases-0.7.4/node_modules/fs-temp/lib/temp.js:121:10)
    at Busboy.<anonymous> (/home/ass-releases-0.7.4/node_modules/multer/lib/read-body.js:70:27)
    at Busboy.emit (node:events:394:28)
    at Busboy.emit (node:domain:470:12)
    at Busboy.emit (/home/ass-releases-0.7.4/node_modules/busboy/lib/main.js:37:33)
    at PartStream.<anonymous> (/home/ass-releases-0.7.4/node_modules/busboy/lib/types/multipart.js:214:13)
    at PartStream.emit (node:events:394:28)
    at PartStream.emit (node:domain:470:12)
    ```
    Assuming that must be the same issue. I'll try downgrading

**Comment by tycrek** [comment]
Ahhh yep that's exactly the error the other user had. No way to fix right now so best workaround is downgrade to Node 14 temporarily.

**Comment by ducky710** [comment]
Gotcha. Glad i'm not crazy. I was so confused why it wasn't working lol. We need a docker image badly man :(

**Comment by tycrek** [comment]
Soon hopefully! https://github.com/tycrek/ass/issues/3#issuecomment-878640525

**Comment by tycrek** [comment]
- Fixed by fs-temp developer: https://github.com/LinusU/fs-temp/pull/6#issuecomment-886049701
- Commit: https://github.com/LinusU/fs-temp/commit/f02bfe3acfec76885b46fc91838b5edcaf1d356a
- Release (for fs-temp): https://github.com/LinusU/fs-temp/releases/tag/v2.0.0

I'll wait a bit for other packages to get their dependencies updated, then re-test with Node 16.
